<?php
// Copy this file to /home/USERNAME/private/config.php on the server.
// Replace the empty value with the hash generated by:
// php scripts/generate-password-hash.php "YourStrongPassword"
// Do not commit the real private/config.php to git.
define('ADMIN_PASSWORD_HASH', '');
