<?php
// Copy this file to private/config.php on the server and replace the empty value
// with the hash generated by scripts/generate-password-hash.php.
// Do not commit the real private/config.php to git.
define('ADMIN_PASSWORD_HASH', '');
